CREATE TABLE lists (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE todos (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	completed BOOL NOT NULL DEFAULT false,
	list INT NOT NULL REFERENCES lists(id)
);